import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Oswald } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});
const robotoMono = Poppins({
	subsets: ["latin"],
	weight: ["100", "300", "400", "500", "600", "700"],
});
const oswald = Oswald({
	variable: "--font-osfalt",
	subsets: ["latin"],
});
const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${oswald.variable} ${robotoMono.className} ${geistMono.variable} antialiased`}
			>
				<NavBar />
				{children}
			</body>
		</html>
	);
}
